[project]
name = "oceangla"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramone Agard", email = "rhagard@wustl.edu" },
    { name = "Joey Scanga", email = "scangjo@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "nibabel>=5.4.2",
    "nilearn>=0.13.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pathvalidate>=3.3.1",
    "progressbar2>=4.5.0",
    "templateflow>=25.1.2",
    "textual>=8.2.4",
    "tomlkit>=0.15.0",
]

[project.scripts]
oceangla = "oceangla.main:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=8.39.0",
    "pyright>=1.1.409",
    "pytest>=9.0.3",
]
