[project]
name = "oceangla"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramone Agard", email = "rhagard@wustl.edu" },
    { name = "Joey Scanga", email = "scangjo@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "nibabel>=5.4.2",
    "nilearn>=0.13.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pathvalidate>=3.3.1",
    "progressbar2>=4.5.0",
    "requests>=2.33.1",
    "templateflow>=25.1.2",
    "textual>=8.2.4",
    "tomlkit>=0.15.0",
]

[project.scripts]
oceangla = "oceangla.main:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=8.39.0",
    "pyright>=1.1.409",
    "pytest>=9.0.3",
]
docs = [
    "sphinx>=9.0.4",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-rtd-theme>=3.1.0",
]

[tool.pdm.version]
source = "scm"
write_to = "oceangla/_version.py"
write_template = "__version__ = '{}'\n"

[tool.pdm.build]
excludes = [
    "tests/",
    "**/*.log",
    "docs/internal_notes.md",
    "mypackage/_temp/*",
    "**/test_out/",
    "**/test_models.txt",
    ".DS_Store",
    "**/*.db",
    "**/*.csv",
    "**/.ruff_cache/",
]
